language: php

php:
  - "7.2.5"
  - "7.3"
  - "7.4"

env:
  matrix:
    - LARAVEL='^7.0'
    - LARAVEL='^7.0' COMPOSER_FLAGS="--prefer-lowest"

install:
  - composer require "illuminate/contracts:${LARAVEL}" --prefer-dist --no-interaction --no-suggest
  - composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
